spring.application.name=48-Spring-boot-MS-circuit_breaker

server.port=8080

#circuit breaker configuration

resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.sliding-window-size=10


#time limiter conf
resilience4j.timelimiter.instances.userService.timeout-duration=3s
