spring.application.name=57-spring-boot-REDIS-CACHE



server.port=5657

#=================database configuration=====================
spring.datasource.url=jdbc:mysql://localhost:3306/user_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#=================redis configuration=====================
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379






