spring.application.name=ecom-express
spring.ai.mcp.server.type=SYNC
spring.main.web-application-type=none
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.name=demo
spring.main.banner-mode=off
server.port=4545


